authentication/api/urls.py
from django.urls import path

from rest_framework.authtoken.views import obtain_auth_token

from . import views

urlpatterns = [
    path('', views.AuthToken.as_view()),
    path('token/', obtain_auth_token)
]

authentication/urls.py
from django.urls import path

from . import views

app_name = 'authentication'
urlpatterns = [
    path('login/', views.userLogin, name='login'),

    path('logout/', views.loggingout, name='logout'),

    path('register/', views.userRegister, name='register'),
]

chat/urls.py
from django.urls import path

from . import views 

app_name = 'chat'
urlpatterns = [
    path('', views.index, name='index'),
    path('clean/', views.cleanChat, name='clean_chat'),
    path('deletemessage/<str:id>/', views.deleteMessage, name='delete'),
]

localChat/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('authentication/', include('authentication.urls')),
    path('', include('chat.urls')),
] + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

authentication/models.py
from django.db import models

# Create your models here.

chat/models.py
from django.db import models

def upload_to(instance, filename):
    return '{filename}'.format(filename=filename)

class Chat(models.Model):
    username = models.CharField(max_length=255, blank=True, null=True)
    message = models.TextField()
    img = models.FileField(upload_to=upload_to, null=True, blank=True)
    created_time = models.DateTimeField(auto_now_add=True)

authentication/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class LoginForm(forms.Form):
  username = forms.CharField(
    widget=forms.TextInput(attrs={
      'class' : 'form-control',
      'autofocus' : True
    }), 
    required=True)
    
  password = forms.CharField(
    widget=forms.PasswordInput(attrs={
    'class' : 'form-control'
    }), 
    required=True)

chat/forms.py
from django import forms

from .models import Chat

class ChatForm(forms.ModelForm):
    message = forms.CharField(widget=forms.TextInput(attrs={
        'class' : 'form-control',
        'autofocus' : True
    }))

    img = forms.FileField(required=False, widget=forms.FileInput(attrs={
        'class' : 'form-control',
    }))

    class Meta:
        model = Chat
        fields = ['message', 'img',]

authentication/api/views.py
from rest_framework import serializers
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework.permissions import IsAuthenticated

from .serializers import UserSerializer

class AuthToken(APIView):
    permission_classes = [IsAuthenticated]

    def get(self, request, format=None):
        context = {
            'user' : str(request.user),
            'auth' : str(request.auth),
        }

        return Response(context)

authentication/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User, Group

from .forms import LoginForm


def userLogin(request):
    if request.user.is_authenticated:
        return redirect('chat:index')

    if request.method == 'POST':
        username = request.POST.get('username').lower()
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect('chat:index')
        else:
            messages.error(request, 'Username or Password filled uncorrect!')

    page = 'login'
    form = LoginForm(request.POST or None)
    context = {
        'form': form,
        'page': page,
    }
    return render(request, 'authentication.html', context)


def userRegister(request):
    if request.user.is_authenticated:
        return redirect('chat:index')

    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.username = user.username.lower()
            group = Group.objects.get(name='user')
            user.save()
            login(request, user)
            user.groups.add(group)
            return redirect('chat:index')

        messages.error(request, 'An error is occurred during registration')

    page = 'register'
    form = UserCreationForm(request.POST or None)
    context = {
        'form': form,
        'page': page,
    }
    return render(request, 'authentication.html', context)


def loggingout(request):
    logout(request)
    return redirect('chat:index')

chat/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required

from .models import Chat
from .forms import ChatForm

from authentication.decorators import allowed_users, unauthenticated_user


@login_required(login_url='/authentication/login/')
def index(request):
    forms = ChatForm()
    if request.method == 'GET':
        chats = Chat.objects.all().order_by('-created_time')
        if request.user.groups.all()[0].name != 'superadmin':
            user = 'user'
        else : user = 'admin'
        context = {
            'chats': chats,
            'forms': forms,
            'user' : user,
        }
        return render(request, 'chat/index.html', context)
    forms = ChatForm(request.POST, request.FILES)
    if forms.is_valid():
        message = forms.save(commit=False)
        message.username = request.user.username
        message.save()
        return redirect('chat:index')
    
    return redirect("chat:index")

@allowed_users(allowed_roles=['superadmin'])
def cleanChat(request):
    Chat.objects.all().delete()
    return redirect('chat:index')

@allowed_users(allowed_roles=['superadmin'])
def deleteMessage(request, id):
    message = Chat.objects.get(id=id)
    message.delete()
    return redirect('chat:index')

authentication/templates/authentication.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  <title>Document</title>
</head>
<body class="bg-light">
  <div class="d-flex justify-content-center align-items-center vh-100">
    <div>
      <form action="" method="post">
        {% csrf_token %}
        <div class="bg-white p-4 rounded-4">

          {% for message in messages %}
          <div class="alert alert-danger w-100 mx-auto w-50">
            {{ message }}
          </div>
          {% endfor %}
          {% if page == 'login' %}
          <label for="">{{ form.username.label }}</label>
          {{ form.username }}
          {{ form.username.errors.0 }}

          <label for="">{{ form.password.label }}</label>
          {{ form.password }}
          {{ form.password.errors.0 }}

          <p class="small text-secondary mt-3 text-center">If you don't have an account,<br> <a href="{% url 'authentication:register' %}">Sign up</a></p>
          <div class="mt-3"><button class="btn btn-success w-100" type="submit">Sign In</button></div>

          {% else %}

          <label for="">{{ form.username.label }}</label>
          {{ form.username }}
          <p class="text-danger mt-1">{{ form.username.errors.0 }}</p>

          <label for="">{{ form.password1.label }}</label>
          {{ form.password1 }}
          <p class="text-danger mt-1">{{ form.password1.errors.0 }}</p>

          <label for="">{{ form.password2.label }}</label>
          {{ form.password2 }}
          <p class="text-danger mt-1">{{ form.password2.errors.0 }}</p>

          <p class="small text-secondary mt-3 text-center">If you already have an account,<br> <a href="{% url 'authentication:login' %}">Sign in</a></p>
          <div class="mt-3"><button class="btn btn-success w-100" type="submit">Sign up</button></div>
          {% endif %}
        </div>
      </form>
    </div>
  </div>

  <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

authentication/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  <title>Document</title>
</head>
<body class="bg-light">
  <div class="d-flex justify-content-center align-items-center vh-100">
    <div>
      <form action="" method="post">
        {% csrf_token %}
        <div class="bg-white p-4 rounded-4">

          {% for message in messages %}
          <div class="alert alert-danger w-100 mx-auto w-50">
            {{ message }}
          </div>
          {% endfor %}

          <label for="">{{ form.username.label }}</label>
          {{ form.username }}
          {{ form.username.errors.0 }}

          <label for="">{{ form.password.label }}</label>
          {{ form.password }}
          {{ form.password.errors.0 }}

          <div class="mt-3"><button class="btn btn-success w-100" type="submit">Log In</button></div>
        </div>
      </form>
    </div>
  </div>

  <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

chat/templates/chat/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>Dedyfo Chat</title>
</head>
<body class="bg-light">
    <div class="container">
        {% for message in messages %}
        <div class="alert alert-danger w-100 mx-auto w-50 mt-3">
          {{ message }}
        </div>
        {% endfor %}
        <div class="d-flex justify-content-end mt-3">
            <button class="btn btn-secondary text-white mx-3" data-bs-toggle="modal" data-bs-target="#exampleModal">Logout</button>
            {% if user == 'admin' %}
            <a href="{% url 'chat:clean_chat' %}"><button class="btn btn-danger text-white">Clean</button></a>
            {% endif %}
        </div>
        
        <!-- Modal -->
        <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">Logout confirmation</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    Dou you really wanna logout?
                </div>
                <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <a href="{% url 'authentication:logout' %}"><button type="button" class="btn btn-success">Confirm</button></a>
                </div>
            </div>
            </div>
        </div>
        <div class="bg-white shadow vh-50 rounded-4 border-3 mt-4 overflow-auto">
            {% for x in chats %}
                <div class="ms-3 d-flex justify-content-between">
                    <div>
                        <p class="fw-bold mb-0 mt-3">{{ x.username }}</p>
                        {{ x.message }}
                        <div>
                            <a href="/media/{{ x.img }}">{{ x.img }}</a>
                        </div>
                        
                    </div>
                    <div class="me-3 mt-3">
                        {% if user == 'admin' %}
                        <a href="{% url 'chat:delete' x.id %}"><button class="btn btn-danger text-light"><svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" fill="currentColor" class="bi bi-trash-fill" viewBox="0 0 16 16">
                            <path d="M2.5 1a1 1 0 0 0-1 1v1a1 1 0 0 0 1 1H3v9a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2V4h.5a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H10a1 1 0 0 0-1-1H7a1 1 0 0 0-1 1H2.5zm3 4a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 .5-.5zM8 5a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7A.5.5 0 0 1 8 5zm3 .5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 1 0z"/>
                          </svg></button></a>
                        {% endif %}
                    </div>
                </div>
            {% endfor %}
        </div>
        <div class="mt-4">
            <form action="" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {{ forms.as_p }}
            <div class="d-flex justify-content-end mt-2">
                <button class="btn btn-success" type="submit">Send</button>
            </div>
            </form>
        </div>
    </div>

    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>